#!/usr/bin/env python3
"""Regenerate the self-hosted webfonts in assets/fonts/ + assets/fonts.css.

You only need this if you want to change which font weights the site ships.
Run it from the repo root:

    python3 tools-regenerate-fonts.py

Google's stylesheet offers a dozen unicode-range subsets per family. This page
is Bangla + English only, so we keep `bengali` for Noto Sans Bengali and
`latin` for both families and drop the rest — that is what keeps the initial
view inside the 3G budget. Bangla faces are ~105KB each, so only regular and
bold are shipped there; CSS rules asking for 600/800 fall back to 700.
"""
import os
import re
import subprocess
import sys
import urllib.request

ROOT = os.path.dirname(os.path.abspath(__file__))
OUT_DIR = os.path.join(ROOT, "assets", "fonts")
CSS_OUT = os.path.join(ROOT, "assets", "fonts.css")

GOOGLE_CSS = (
    "https://fonts.googleapis.com/css2"
    "?family=Inter:wght@400;700;800"
    "&family=Noto+Sans+Bengali:wght@400;700"
    "&display=swap"
)
# A desktop UA is required, otherwise Google serves the older ttf/woff format.
UA = ("Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0 Safari/537.36")

# family -> (subsets to keep, weights to keep)
KEEP = {
    "Noto Sans Bengali": ({"bengali", "latin"}, {"400", "700"}),
    "Inter": ({"latin"}, {"400", "700", "800"}),
}


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    req = urllib.request.Request(GOOGLE_CSS, headers={"User-Agent": UA})
    css = urllib.request.urlopen(req).read().decode("utf-8")

    # Each block in Google's CSS looks like:  /* subset */\n@font-face { ... }
    blocks = re.findall(r"/\*\s*([a-z0-9\-\[\]]+)\s*\*/\s*(@font-face\s*\{.*?\})", css, re.S)
    if not blocks:
        sys.exit("could not parse the Google Fonts stylesheet")

    out = ["/* CafeTrack — self-hosted webfonts. Bangla + Latin subsets only.",
           "   Generated by tools-regenerate-fonts.py — do not edit by hand. */", ""]
    seen = set()

    for subset, block in blocks:
        fam = re.search(r"font-family:\s*'([^']+)'", block).group(1)
        weight = re.search(r"font-weight:\s*(\d+)", block).group(1)
        if fam not in KEEP:
            continue
        subsets, weights = KEEP[fam]
        if subset not in subsets or weight not in weights:
            continue

        url = re.search(r"url\((https://[^)]+\.woff2)\)", block).group(1)
        fname = f"{fam.lower().replace(' ', '-')}-{subset}-{weight}.woff2"
        if fname not in seen:
            path = os.path.join(OUT_DIR, fname)
            if subprocess.run(["curl", "-sS", "-f", url, "-o", path]).returncode != 0:
                sys.exit(f"download failed: {url}")
            seen.add(fname)

        urange = re.search(r"unicode-range:\s*([^;]+);", block)
        out += ["@font-face{",
                f"  font-family:'{fam}';",
                "  font-style:normal;",
                f"  font-weight:{weight};",
                "  font-display:swap;",
                f"  src:url('fonts/{fname}') format('woff2');"]
        if urange:
            out.append(f"  unicode-range:{urange.group(1).strip()};")
        out.append("}")

    with open(CSS_OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(out) + "\n")

    total = sum(os.path.getsize(os.path.join(OUT_DIR, f)) for f in seen)
    for f in sorted(seen):
        print(f"  {f}  {os.path.getsize(os.path.join(OUT_DIR, f)) // 1024} KB")
    print(f"{len(seen)} files, {total // 1024} KB total")


if __name__ == "__main__":
    main()
